sudo: required
dist: trusty
language: bash
before_script:
- sudo apt-get update -qq
- sudo apt-get install make curl zip unzip check -qq
script:
- make
notifications:
  email: false
deploy:
  provider: releases
  file: AlpineGitLFS.zip
  on:
    repo: binarylandscapes/AlpineWSL
    tags: true
    all_branches: true
  skip_cleanup: true
